### ISSUE TITLE
support

### ISSUE THREAD

**Issue by finder0009** [ImpulseAdventure/GUIslice#168] opened 2019-09-10 20:53 UTC
NOTE: For issues with the GUIslice Builder, please file a report instead at:
https://github.com/ImpulseAdventure/GUIslice-Builder-source/issues
win7 32bit installer

**Comment by ImpulseAdventure** [comment] 2019-09-11 05:15
Closing as duplicate of https://github.com/ImpulseAdventure/GUIslice-Builder-source/issues/31

**Closed by ImpulseAdventure** 2019-09-11 05:15 UTC
