### ISSUE TITLE
ESP 32 Font Problem

### ISSUE THREAD

**Issue by feendrache** [ImpulseAdventure/GUIslice#174] opened 2019-11-22 16:24 UTC
### Describe the bug
- Okey, i changed my display from an elegoo to an spi one and need to rebuild my GUI since the old one won't work in the esp32 with the spi display
- My Problem now: only the BuiltinFonts are working, no displaying of text on the display when i select one of the other fonts

### Device hardware
- *MCU*: ESP32
- *Display with link*: 2.8'' SPi Display with touch, red one generic
- *GUIslice config selected*: esp-tftespi-default-xpt2046_int

*Please confirm whether:*
- *Display works correctly with standalone display driver library examples (eg. TFT_eSPI graphicstest, Adafruit graphicstest, etc.) without GUIslice:* yes
- *Touch works correctly with standalone touch library examples without GUIslice:* yes

### Expected behavior
Well i wanted to use other fonts.. 
took me some time to realise that this was the problem

### Initialization messages
no errors

**Comment by ImpulseAdventure** [comment] 2019-11-23 19:59
Hi @feendrache --

Can you confirm an example of a font that you are trying to use? (ie. is it included within the [TFT_eSPI/Fonts/GFXFF](https://github.com/Bodmer/TFT_eSPI/tree/master/Fonts/GFXFF) directory?)

If so, can you confirm that the GUIslice example **ex04** works using the TFT_eSPI freefonts? (we would like to test it first without the Builder)
- **`/examples/arduino/ex04_ard_ctrls.ino`**
- Uncomment the `#define USE_EXTRA_FONTS` line
- Does the "Quit" button now use the larger font? (it should use `FreeSansBold12pt7b`)

thanks

**Comment by feendrache** [comment] 2019-11-23 20:25
Yeah that'S working just fine

**Comment by ImpulseAdventure** [comment] 2019-11-25 07:08
If you are seeing `ex04` work fine with TFT_eSPI custom fonts then the problem is likely that the Builder is not set to TFT_eSPI output mode. The TFT_eSPI display library handles fonts differently from other libraries, so the Builder needs to be in a special mode to generate the correct font initialization.

Please check the setting in the Builder's **Edit -> Options -> Target Platform**; it should be set to `arduino TFT_eSPI`. Does this help?

![image](https://user-images.githubusercontent.com/8510097/69519556-3537d900-0f0f-11ea-9bec-1ab167b3db8d.png)

I'm not sure if we documented this visibly so perhaps a wiki documentation update might be necessary.

**Comment by ImpulseAdventure** [comment] 2019-11-30 16:03
Closing as I expect that the above Builder option will address the original issue.

**Closed** 2019-11-30 16:03 UTC
Labels: Builder
